# Generated by Django 3.2.5 on 2022-01-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200)),
                ('customer_type', models.CharField(max_length=300)),
                ('person_transacted', models.CharField(blank=True, max_length=200)),
                ('rate1', models.IntegerField(default=0)),
                ('rate2', models.IntegerField(default=0)),
                ('rate3', models.IntegerField(default=0)),
                ('rate4', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
