# Generated by Django 4.0 on 2022-01-06 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cssurvey', '0003_alter_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
    ]
