# Generated by Django 4.0 on 2022-01-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssurvey', '0004_remove_question_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedback',
            name='rate5',
            field=models.IntegerField(default=0),
        ),
    ]
