# Generated by Django 4.0.3 on 2022-03-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssurvey', '0005_customerfeedback_rate5'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbCmuoffices',
            fields=[
                ('officeid', models.AutoField(db_column='officeID', primary_key=True, serialize=False)),
                ('officename', models.TextField(blank=True, db_column='officeName', null=True)),
                ('officecode', models.TextField(blank=True, db_column='officeCode', null=True)),
                ('scope', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_cmuoffices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCmuofficials',
            fields=[
                ('officerid', models.AutoField(db_column='officerID', primary_key=True, serialize=False)),
                ('fname', models.TextField(blank=True, null=True)),
                ('minitial', models.TextField(blank=True, null=True)),
                ('lname', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('signatories', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_cmuofficials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCoverage',
            fields=[
                ('coverageid', models.AutoField(db_column='coverageID', primary_key=True, serialize=False)),
                ('from_field', models.DateField(db_column='from')),
                ('to', models.DateField()),
            ],
            options={
                'db_table': 'tb_coverage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCssrespondents',
            fields=[
                ('respondentid', models.AutoField(db_column='respondentID', primary_key=True, serialize=False)),
                ('respondentname', models.TextField(blank=True, db_column='respondentName', null=True)),
                ('respondenttype', models.TextField(blank=True, db_column='respondentType', null=True)),
                ('responddate', models.DateField(auto_now_add=True, db_column='respondDate', null=True)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_cssrespondents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCssrespondentsDetails',
            fields=[
                ('crid', models.AutoField(db_column='CRID', primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tb_cssrespondents_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbEmployees',
            fields=[
                ('eid', models.AutoField(db_column='EID', primary_key=True, serialize=False)),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('office_id', models.IntegerField(blank=True, null=True)),
                ('job_position', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbLogs',
            fields=[
                ('logid', models.AutoField(db_column='logID', primary_key=True, serialize=False)),
                ('accountid', models.IntegerField(db_column='accountID')),
                ('activity', models.TextField()),
                ('datetime', models.TextField()),
            ],
            options={
                'db_table': 'tb_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbQuestions',
            fields=[
                ('qid', models.AutoField(db_column='QID', primary_key=True, serialize=False)),
                ('survey_question', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreated', models.DateTimeField(blank=True, db_column='dateCreated', null=True)),
                ('display_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_questions',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CustomerFeedback',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
