# Generated by Django 4.0.3 on 2022-03-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cssurvey', '0006_tbcmuoffices_tbcmuofficials_tbcoverage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbemployees',
            options={},
        ),
    ]
