# Generated by Django 4.0.3 on 2022-03-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cssurvey', '0007_alter_tbemployees_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbemployees',
            options={'managed': False},
        ),
    ]
