# Generated by Django 4.0.3 on 2022-04-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssurvey', '0008_alter_tbemployees_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('complaint', models.TextField(blank=True, null=True)),
                ('date_filed', models.DateTimeField(auto_now_add=True, db_column='dateCreated')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('is_starred', models.IntegerField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
    ]
